### ISSUE TITLE
Cloudant URL Entry stops the application from working locally

### ISSUE THREAD

**Issue by freeOuss** [watson-developer-cloud/food-coach#21]
I have faced the following issue while running the app locally.
```
 assert.js:42
   throw new errors.AssertionError({
   ^
 
 AssertionError [ERR_ASSERTION]: url is not valid
     at dbScope (/home/frijiman/Documents/IBM_Watson_Lab/SecondSession/food-coach-master/node_modules/nano/lib/nano.js:36:10)
     at Object.<anonymous> (/home/frijiman/Documents/IBM_Watson_Lab/SecondSession/food-coach-master/app.js:197:29)
     at Module._compile (module.js:652:30)
     at Object.Module._extensions..js (module.js:663:10)
     at Module.load (module.js:565:32)
     at tryModuleLoad (module.js:505:12)
     at Function.Module._load (module.js:497:3)
     at Module.require (module.js:596:17)
     at require (internal/module.js:11:18)
     at Object.<anonymous> (/home/frijiman/Documents/IBM_Watson_Lab/SecondSession/food-coach-master/server.js:6:14)
     at Module._compile (module.js:652:30)
     at Object.Module._extensions..js (module.js:663:10)
     at Module.load (module.js:565:32)
     at tryModuleLoad (module.js:505:12)
     at Function.Module._load (module.js:497:3)
     at Function.Module.runMain (module.js:693:10)
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! food-coach@0.2.1 start: `node server.js`
 npm ERR! Exit status 1
 npm ERR! 
 npm ERR! Failed at the food-coach@0.2.1 start script.
```
The issue was resolved when removing the Cloudant entry from my .env file.
Please remove it from your env.example file for future releases.

**Comment by germanattanasio** [comment]
This was fixed a while back. We only add the cloudant routes if `process.env.CLOUDANT_URL` is present
