### ISSUE TITLE
Problems with runing on Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by VGGatGitHub** [watson-developer-cloud/food-coach#31]
I am try the food-coach demo on Ubuntu 18.04.2 LTS but got the following errors when doing the Running locally section:

npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7
npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7

npm start
> @ibm-watson/food-coach@0.2.1 start /home/vesselin/IBM/food-coach-master
> node server.js

assert.js:42
  throw new errors.AssertionError({
  ^
AssertionError [ERR_ASSERTION]: url is not valid
    at dbScope (/home/vesselin/IBM/food-coach-master/node_modules/nano/lib/nano.js:36:10)
    at Object.<anonymous> (/home/vesselin/IBM/food-coach-master/app.js:196:29)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/vesselin/IBM/food-coach-master/server.js:6:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

npm ERR! Linux 4.15.0-46-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! @ibm-watson/food-coach@0.2.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ibm-watson/food-coach@0.2.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @ibm-watson/food-coach package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @ibm-watson/food-coach
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @ibm-watson/food-coach
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vesselin/IBM/food-coach-master/npm-debug.log

**Comment by VGGatGitHub** [comment]
Can you advise on how to overcome this problem above or the memory issue below? 
I tried to run it as a Cloud Foundry Application as well but there I run in memory issues
"An error occurred performing the operation. Try again later. Description: You have exceeded your organization's memory limit: app requested more memory than available"
which I am hoping to resolve via the IBM support...
