### ISSUE TITLE
Failed to deploy the sample code using steps in instruction.

### ISSUE THREAD

**Issue by ibmalan** [watson-developer-cloud/food-coach#6]
2016-10-26T05:08:34.57-0500 [App/0]      ERR module.js:327
2016-10-26T05:08:34.57-0500 [App/0]      ERR     throw err;
2016-10-26T05:08:34.57-0500 [App/0]      ERR     ^
2016-10-26T05:08:34.57-0500 [App/0]      ERR Error: Cannot find module 'async'
2016-10-26T05:08:34.57-0500 [App/0]      ERR     at Function.Module._resolveFilename (module.js:325:15)
2016-10-26T05:08:34.57-0500 [App/0]      ERR     at Function.Module._load (module.js:276:25)
2016-10-26T05:08:34.57-0500 [App/0]      ERR     at Module.require (module.js:353:17)
2016-10-26T05:08:34.57-0500 [App/0]      ERR     at require (internal/module.js:12:17)
2016-10-26T05:08:34.57-0500 [App/0]      ERR     at Object.<anonymous> (/home/vcap/app/node_modules/watson-developer-cloud/speech-to-text/v1.js:32:13)
2016-10-26T05:08:34.57-0500 [App/0]      ERR     at Module._compile (module.js:409:26)
2016-10-26T05:08:34.57-0500 [App/0]      ERR     at Object.Module._extensions..js (module.js:416:10)
2016-10-26T05:08:34.57-0500 [App/0]      ERR     at Module.load (module.js:343:32)
2016-10-26T05:08:34.57-0500 [App/0]      ERR     at Function.Module._load (module.js:300:12)
2016-10-26T05:08:34.57-0500 [App/0]      ERR     at Module.require (module.js:353:17)
2016-10-26T05:08:34.57-0500 [App/0]      ERR     at require (internal/module.js:12:17)
2016-10-26T05:08:34.59-0500 [App/0]      ERR npm ERR! Linux 3.19.0-33-generic
2016-10-26T05:08:34.59-0500 [App/0]      ERR npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
2016-10-26T05:08:34.59-0500 [App/0]      ERR npm ERR! node v4.6.0
2016-10-26T05:08:34.59-0500 [App/0]      ERR npm ERR! npm  v2.15.9
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR! code ELIFECYCLE
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR! food-coach@0.2.1 start: `node server.js`
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR! Exit status 1
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR! 
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR! Failed at the food-coach@0.2.1 start script 'node server.js'.
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR! This is most likely a problem with the food-coach package,
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR! not with npm itself.
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR! Tell the author that this fails on your system:
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR!     node server.js
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR! You can get information on how to open an issue for this project with:
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR!     npm bugs food-coach
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR! Or if that isn't available, you can get their info via:
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR! 
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR!     npm owner ls food-coach
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR! There is likely additional logging output above.
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR! Please include the following file with any support request:
2016-10-26T05:08:34.60-0500 [App/0]      ERR npm ERR!     /home/vcap/app/npm-debug.log
2016-10-26T05:08:34.67-0500 [DEA/66]     ERR Instance (index 0) failed to start accepting connections
2016-10-26T05:08:34.71-0500 [API/0]      OUT App instance exited with guid c0539322-e800-4693-be53-76dc93b9535c payload: {"cc_partition"=>"default", "droplet"=>"c0539322-e800-4693-be53-76dc93b9535c", "version"=>"b7443ed6-ee0d-4107-8411-d28f91589cd3", "instance"=>"231683ba4d2c40d3a1048cf3f5bcc849", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1477476514}
2016-10-26T05:08:34.72-0500 [API/4]      OUT App instance exited with guid c0539322-e800-4693-be53-76dc93b9535c payload: {"cc_partition"=>"default", "droplet"=>"c0539322-e800-4693-be53-76dc93b9535c", "version"=>"b7443ed6-ee0d-4107-8411-d28f91589cd3", "instance"=>"231683ba4d2c40d3a1048cf3f5bcc849", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1477476514}
[food-coach.txt](https://github.com/watson-developer-cloud/food-coach/files/553051/food-coach.txt)

**Comment by germanattanasio** [comment]
This was due to a problem in the node-sdk which was already fixed.

**Comment by germanattanasio** [comment]
See: watson-developer-cloud/node-sdk#330

**Comment by ibmalan** [comment]
need to change the watson-developer-cloud version to 2.6.2 in package.json
 "watson-developer-cloud": "2.6.2"

**Comment by maggierui** [comment]
I changed the watson-developer-cloud version to 2.6.2 in package.json as instructed above, but I still got the error: 
Failed at the food-coach@0.2.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the food-coach package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs food-coach
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls food-coach
npm ERR! There is likely additional logging output above.

**Comment by pablitos92** [comment]
Hi, is possible to connect this service to Tezt to speech and speech to text?
I want to make a similat think but giving users the possibility to talk directly with their voice
